apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-cluster
spec:
  members: 3
  type: ReplicaSet
  version: "6.0.13"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: root
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: mongo-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram    
    - name: pgsdb
      db: pgsproddb
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: mongo-password
      roles:
        - name: dbAdminAnyDatabase
          db: pgsproddb
        - name: dbOwner
          db: pgsproddb
        - name: clusterAdmin
          db: pgsproddb    
      scramCredentialsSecretName: my-scram1
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongod
              resources:
                limits:
                  cpu: "200m"
                  memory: 900M             
                requests:
                  cpu: "100m"
                  memory: 800M
            - name: mongodb-agent
              resources:
                requests:
                  cpu: "10m"
                  memory: 100M
              readinessProbe:
                failureThreshold: 60
                initialDelaySeconds: 120
                timeoutSeconds: 20       
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            resources:            
              requests:
                storage: 1Gi
            storageClassName: "mongo-staging"    
            volumeMode : Filesystem
#            volumeName: mongodatapv
            accessModes:
              - ReadWriteOnce
        - metadata:
            name: logs-volume
          spec:
            resources:
              requests:
                storage: 100Mi
            volumeMode : Filesystem
            storageClassName: "mongo-staging"
#            volumeName: mongo-log-pv
            accessModes:
              - ReadWriteOnce        

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-password
type: Opaque
stringData:
  password: mongodb
